name: ExtUtils-Manifest

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"
          distribution: strawberry
      - name: perl version
        shell: bash
        run: |
          PATH="/c/hostedtoolcache/windows/strawberry-perl/5.32.1/x64/perl/bin:$PATH"
          (
            echo "# Path"
            echo $PATH
            echo "# Perl"
            command -v perl
            echo '# Perl version'
            perl -V 2>&1
          ) | tee -a "$GITHUB_STEP_SUMMARY"
      - name: cpanm ExtUtils::Manifest
        shell: bash
        run: |
          PATH="/c/hostedtoolcache/windows/strawberry-perl/5.32.1/x64/perl/bin:$PATH"
          (
            echo '# cpanm install phase'
            cpanm -v ExtUtils::Manifest 2>&1
          ) | tee -a "$GITHUB_STEP_SUMMARY"
