name: ExtUtils-Manifest

on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: perl version
        shell: bash
        run: |
          (
            echo '# Perl version'
            perl -V 2>&1
          ) | tee -a "$GITHUB_STEP_SUMMARY"
      - name: cpanm ExtUtils::Manifest
        shell: bash
        run: |
          (
            echo '# cpanm install phase'
            cpanm -v ExtUtils::Manifest 2>&1
          ) | tee -a "$GITHUB_STEP_SUMMARY"
